/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
}
export interface BroadbandPlan {
  'id' : bigint,
  'name' : string,
  'speedMbps' : bigint,
  'description' : string,
  'isUnlimited' : boolean,
  'isActive' : boolean,
  'priceMonthly' : number,
}
export interface ChannelPackage {
  'id' : bigint,
  'name' : string,
  'tier' : string,
  'description' : string,
  'channels' : Array<string>,
  'isActive' : boolean,
  'priceMonthly' : number,
}
export interface SubscriberProfile {
  'subscribedPackageIds' : Array<bigint>,
  'joinedAt' : bigint,
  'fullName' : string,
  'address' : string,
  'phoneNumber' : string,
  'subscribedPlanIds' : Array<bigint>,
}
export interface UserProfile {
  'subscribedPackageIds' : Array<bigint>,
  'joinedAt' : bigint,
  'fullName' : string,
  'address' : string,
  'phoneNumber' : string,
  'subscribedPlanIds' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], bigint>,
  'createBroadbandPlan' : ActorMethod<[BroadbandPlan], bigint>,
  'createChannelPackage' : ActorMethod<[ChannelPackage], bigint>,
  'createOrUpdateProfile' : ActorMethod<[SubscriberProfile], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteBroadbandPlan' : ActorMethod<[bigint], undefined>,
  'deleteChannelPackage' : ActorMethod<[bigint], undefined>,
  'getActiveBroadbandPlans' : ActorMethod<[], Array<BroadbandPlan>>,
  'getActiveChannelPackages' : ActorMethod<[], Array<ChannelPackage>>,
  'getAllSubscribers' : ActorMethod<[], Array<SubscriberProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], [] | [SubscriberProfile]>,
  'getPublishedAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'subscribeToPackage' : ActorMethod<[bigint], undefined>,
  'subscribeToPlan' : ActorMethod<[bigint], undefined>,
  'unsubscribeFromPackage' : ActorMethod<[bigint], undefined>,
  'unsubscribeFromPlan' : ActorMethod<[bigint], undefined>,
  'updateAnnouncement' : ActorMethod<[bigint, Announcement], undefined>,
  'updateBroadbandPlan' : ActorMethod<[bigint, BroadbandPlan], undefined>,
  'updateChannelPackage' : ActorMethod<[bigint, ChannelPackage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];