/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
});
export const BroadbandPlan = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'speedMbps' : IDL.Nat,
  'description' : IDL.Text,
  'isUnlimited' : IDL.Bool,
  'isActive' : IDL.Bool,
  'priceMonthly' : IDL.Float64,
});
export const ChannelPackage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'channels' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'priceMonthly' : IDL.Float64,
});
export const SubscriberProfile = IDL.Record({
  'subscribedPackageIds' : IDL.Vec(IDL.Nat),
  'joinedAt' : IDL.Int,
  'fullName' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'subscribedPlanIds' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'subscribedPackageIds' : IDL.Vec(IDL.Nat),
  'joinedAt' : IDL.Int,
  'fullName' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'subscribedPlanIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
  'createBroadbandPlan' : IDL.Func([BroadbandPlan], [IDL.Nat], []),
  'createChannelPackage' : IDL.Func([ChannelPackage], [IDL.Nat], []),
  'createOrUpdateProfile' : IDL.Func([SubscriberProfile], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteBroadbandPlan' : IDL.Func([IDL.Nat], [], []),
  'deleteChannelPackage' : IDL.Func([IDL.Nat], [], []),
  'getActiveBroadbandPlans' : IDL.Func([], [IDL.Vec(BroadbandPlan)], ['query']),
  'getActiveChannelPackages' : IDL.Func(
      [],
      [IDL.Vec(ChannelPackage)],
      ['query'],
    ),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(SubscriberProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(SubscriberProfile)], ['query']),
  'getPublishedAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'subscribeToPackage' : IDL.Func([IDL.Nat], [], []),
  'subscribeToPlan' : IDL.Func([IDL.Nat], [], []),
  'unsubscribeFromPackage' : IDL.Func([IDL.Nat], [], []),
  'unsubscribeFromPlan' : IDL.Func([IDL.Nat], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Nat, Announcement], [], []),
  'updateBroadbandPlan' : IDL.Func([IDL.Nat, BroadbandPlan], [], []),
  'updateChannelPackage' : IDL.Func([IDL.Nat, ChannelPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
  });
  const BroadbandPlan = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'speedMbps' : IDL.Nat,
    'description' : IDL.Text,
    'isUnlimited' : IDL.Bool,
    'isActive' : IDL.Bool,
    'priceMonthly' : IDL.Float64,
  });
  const ChannelPackage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'channels' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'priceMonthly' : IDL.Float64,
  });
  const SubscriberProfile = IDL.Record({
    'subscribedPackageIds' : IDL.Vec(IDL.Nat),
    'joinedAt' : IDL.Int,
    'fullName' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'subscribedPlanIds' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'subscribedPackageIds' : IDL.Vec(IDL.Nat),
    'joinedAt' : IDL.Int,
    'fullName' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'subscribedPlanIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
    'createBroadbandPlan' : IDL.Func([BroadbandPlan], [IDL.Nat], []),
    'createChannelPackage' : IDL.Func([ChannelPackage], [IDL.Nat], []),
    'createOrUpdateProfile' : IDL.Func([SubscriberProfile], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteBroadbandPlan' : IDL.Func([IDL.Nat], [], []),
    'deleteChannelPackage' : IDL.Func([IDL.Nat], [], []),
    'getActiveBroadbandPlans' : IDL.Func(
        [],
        [IDL.Vec(BroadbandPlan)],
        ['query'],
      ),
    'getActiveChannelPackages' : IDL.Func(
        [],
        [IDL.Vec(ChannelPackage)],
        ['query'],
      ),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(SubscriberProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(SubscriberProfile)], ['query']),
    'getPublishedAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'subscribeToPackage' : IDL.Func([IDL.Nat], [], []),
    'subscribeToPlan' : IDL.Func([IDL.Nat], [], []),
    'unsubscribeFromPackage' : IDL.Func([IDL.Nat], [], []),
    'unsubscribeFromPlan' : IDL.Func([IDL.Nat], [], []),
    'updateAnnouncement' : IDL.Func([IDL.Nat, Announcement], [], []),
    'updateBroadbandPlan' : IDL.Func([IDL.Nat, BroadbandPlan], [], []),
    'updateChannelPackage' : IDL.Func([IDL.Nat, ChannelPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };